### PR TITLE
Main logo fixes

### PR DESCRIPTION
**Pull request by Roy-Orbison**
- Smaller as SVG (~4kB instead of ~7kB)
- Moved bg image to h1 for improved theme compatibility (bg colors set on h1 were wiped out)
- RTL support

FYI, I manually edited your official logo to extract the icon, but then used a [minifier](https://www.svgminify.com/) and [data-url encoder](https://yoksel.github.io/url-encoder/), which is a neat trick to get results smaller than base64.

### CODE REVIEW

**Comment by LionelLaffineur** [comment]
Thanks for your contribution @Roy-Orbison  !
Would it be useful to you to use the original SVG for the logo ?  The text should, in this case, not be used.
logo

**Comment by Roy-Orbison** [comment]
That's the logo I used to extract the icon from. You can test the data URI in the commit by copying and pasting it in your browser's address bar:
``` none
data:image/svg+xml,%3C%3Fxml version='1.0' encoding='UTF-8'%3F%3E%3Csvg width='32' height='32' version='1.1' viewBox='64.7 124.1 80.9 96.4' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m103.41 219.69c-5.8574-2.8071-15.54-10.873-20.554-17.123-8.4331-10.511-13.554-22-16.256-36.469-0.61313-3.2837-0.94886-7.2042-1.3892-16.222-0.49913-10.223-0.51449-13.203-0.06891-13.372 0.21381-0.0812 2.4952-0.48891 5.0697-0.9064 13.6-2.2054 20.623-4.4565 32.562-10.438 2.405-1.2048 2.0374-1.2525 6.2745 0.81404 11.41 5.5651 17.35 7.4133 30.893 9.6133 1.4204 0.23065 3.1637 0.5438 3.8739 0.6957l1.2913 0.27615 0.0503 1.1299c0.18503 4.1624-0.92338 23-1.6052 27.279-3.0098 18.889-11.655 34.733-25.401 46.551-5.2062 4.476-7.3971 6.017-11.166 7.8534-2.1324 1.0391-2.0779 1.0343-3.5755 0.3166zm2.9787-3.3031c6.1816-2.8968 15.622-10.943 20.558-17.522 7.8262-10.432 12.201-20.542 14.378-33.229 0.75313-4.3896 1.7534-20.732 1.5769-25.763l-0.0537-1.5295-1.5334-0.2868c-0.84339-0.1578-2.6956-0.46995-4.116-0.69376-11.476-1.8083-17.455-3.6872-28.486-8.9523-3.9955-1.9071-3.5582-1.8595-5.9706-0.65024-10.907 5.4675-17.902 7.6897-30.755 9.7708-2.4858 0.4025-4.6474 0.77143-4.8036 0.81989-0.32192 0.0998-0.3193 0.30415 0.13497 10.557 0.44397 10.021 0.80438 14.248 1.5136 17.752 4.0571 20.047 12.361 33.554 28.093 45.694 2.0354 1.5708 7.3043 4.6699 7.9393 4.6699 0.0905 0 0.7763-0.2867 1.524-0.63714z' fill='%232d4159' stroke-width='0'/%3E%3Cg fill='none' stroke='%232d4159' stroke-linecap='round'%3E%3Cpath d='m117.12 167.89h10.555' stroke-width='1.5366'/%3E%3Cpath d='m82.309 167.91h15.836' stroke-width='1.5366'/%3E%3Cpath d='m117.21 173.98c3.4115-9e-3 6.822-0.0178 8.5265 2.5195s1.7043 7.6198 1.704 12.701' stroke-linejoin='round' stroke-width='2.0479'/%3E%3C/g%3E%3Ca transform='matrix(1.3101,0,0,1.3101,-32.778,-49.614)' stroke-width='2.2613'%3E%3Cpath d='m102.94 183.03c-3.5765-0.48481-6.4446-3.0846-7.2878-6.6062-0.24955-1.0422-0.24955-15.526 0-16.569 0.78951-3.2971 3.3213-5.7688 6.6636-6.5054 0.90662-0.1998 4.7806-0.1998 5.6872 0 3.3422 0.73656 5.8741 3.2083 6.6636 6.5054 0.24956 1.0422 0.24956 15.526 0 16.569-0.78643 3.2843-3.2115 5.8758-6.5248 6.608-0.62799 0.13877-4.4 0.10692-5.2017-2e-3zm4.8475-1.2499c3.0163-0.68834 5.2113-2.9219 5.7878-5.8896 0.10298-0.53012 0.11102-0.88647 0.11102-4.9205v-4.349h-17.054v4.349c0 4.034 8e-3 4.3904 0.11102 4.9205 0.60507 3.1148 3.0017 5.4265 6.1674 5.9488 0.72013 0.1188 4.2865 0.0756 4.8767-0.0591zm-3.2122-17.428c0-1.1003 0-1.1003-0.1459-1.1668-0.23048-0.10501-0.66958-0.53783-0.80808-0.7965-0.1736-0.32424-0.22738-3.2901-0.0683-3.7689 0.11347-0.34163 0.48553-0.78056 0.79582-0.93886l0.2265-0.11555v-3.2264l-0.77385 0.0317c-3.5466 0.14528-6.388 2.5676-7.058 6.0171-0.0973 0.50068-0.11102 0.84993-0.11102 2.818v2.2465h7.9429zm9.111-1.1462c0-1.9681-0.0138-2.3173-0.11102-2.818-0.6701-3.4496-3.5114-5.8718-7.058-6.0171l-0.77385-0.0317v3.2264l0.2265 0.11555c0.30422 0.1552 0.67838 0.59148 0.79118 0.92253 0.1538 0.45138 0.13354 3.2291-0.0267 3.6574-0.12251 0.32742-0.54083 0.78574-0.84273 0.9233-0.14828 0.0676-0.14828 0.0676-0.14828 1.1678v1.1003h7.9429z' fill='%232d4159' stroke-width='2.2613'/%3E%3C/a%3E%3Cg fill='none' stroke='%232d4159' stroke-linecap='round' stroke-linejoin='round' stroke-width='2.0479'%3E%3Cpath d='m92.778 174.02c-3.4115-9e-3 -6.8219-0.0178-8.5265 2.5195s-1.7043 7.6198-1.704 12.701'/%3E%3Cpath d='m117.22 163.17c3.4115 9e-3 6.822 0.0178 8.5265-2.5195 1.7046-2.5373 1.7043-7.6198 1.704-12.701'/%3E%3Cpath d='m92.793 163.13c-3.4115 9e-3 -6.8219 0.0178-8.5265-2.5195s-1.7043-7.6198-1.704-12.701'/%3E%3C/g%3E%3C/svg%3E%0A
```
I notice you've added a lot of base64-encoded high-resolution PNG icons to the updated design. This is great but I think they would benefit from similar replacement with similarly optimised versions of (I assume) their SVG originals.

**Review by LionelLaffineur — APPROVED** [review]
Thanks for your contribution.  I'll try to improve icons to svg.

**Comment by OmlineEditor** [comment]
can you reduce the size of the logo even more? Here's an even smaller size for you:

[logo_new.zip](https://github.com/adminerevo/adminerevo/files/14397245/logo_new.zip)

**Pull request merged**
