### PR TITLE
Filter removal buttons on table select pages

### PR DESCRIPTION
**Pull request by Roy-Orbison**
adminer-filter-x

### CODE REVIEW

**Comment by LionelLaffineur** [comment]
Thanks a lot !  Great !

**Comment by adrianbj** [comment]
@Roy-Orbison @LionelLaffineur - I like this feature, but I think it should remove the filter from the URL query string as well. It doesn't feel right to me the way it is because a page reload will bring the removed filter(s) back.

**Comment by adrianbj** [comment]
Or maybe it's OK as is because adding filters requires the actual search to happen before the query string is updated so maybe removing should behave the same way? I guess there aren't really any other examples where the query string is updated without a page reload. Maybe at some point there was some `history.pushState` (https://github.com/adminerevo/adminerevo/blob/2eba0b515455ba38973d4966354df0f45a8abdfd/changes.txt#L679), but then that functionality was removed?

**Comment by Roy-Orbison** [comment]
@adrianbj It would be an enormous mistake to perform pre-emptive queries before a user had finished modifying their criteria. On large datasets, multiple filter changes would basically DoS the DB server. There only way to know what query the user wants to perform is to wait for form submission.

**Comment by adrianbj** [comment]
@Roy-Orbison - just to clarify, I wasn't talking about doing any queries. I was just suggesting using `history.pushState` to update the query string in the URL so that a page reload would match the state of the filters, but I see that's not really possible given the way things currently work. Anyway, sorry for the confusion - I really was off on a pointless tangent :)

**Comment by Roy-Orbison** [comment]
Interesting. It would be technically possible to use `pushState` once, then `replaceState` for all further changes until a query was executed so that one could "edit" the current URL but preserve history, thus get something like your description. Reloading that page would perform the query, though, even if it wasn't finished being edited. I think it's a lot more work than anyone's likely to do.

**Pull request merged**
