### PR TITLE
Consistent filter remove buttons

### PR DESCRIPTION
**Pull request by Roy-Orbison**
Match row removal buttons on alter table screens.

Further to #77.

### CODE REVIEW

**Comment by Roy-Orbison** [comment]
Don't merge this yet, it breaks filter form submission by hitting <kbd>Enter</kbd>. What's the best way to use the existing close button style but not interfere with submission? :thinking:

**Comment by Roy-Orbison** [comment]
Making a hidden default submit button appear earlier in the DOM appears to be sufficient to get around the issue.

I think it looks better and can rely on themes' existing rules.

**Comment by Roy-Orbison** [comment]
I think so. I know the hidden button is a bit of a hack, but it should not affect usability. What was your opinion when you tried it out?

**Comment by LionelLaffineur** [comment]
Great, thanks a lot !

**Pull request merged**
